def render_help(program_name: str = "python -m notes_app.cli.main") -> str:
    return (
        "Future Proof Notes CLI (phase-1 starter)\n\n"
        f"Usage: {program_name} [command]\n\n"
        "Commands:\n"
        "  help  Show this help text\n"
        "  list  List notes with metadata\n"
        "  search <query>  Search title, tags, author, status, priority, and note body\n"
        "  create <title> <content> [--tags \"t1,t2\"] [--author \"name\"] [--status draft|active|complete] [--priority 1|2|3|4|5]  Create a note\n"
        "  read <id|number>  Display a note by id, filename, or list number\n"
        "  update <id> [--title \"...\"] [--tags \"tag1,tag2\"] [--author \"...\"] [--status draft|active|complete] [--priority 1|2|3|4|5 (1=High,3=Normal,5=Low)] [--content \"...\"]  Update a note\n"
        "  delete <id>  Delete a note by id or filename\n"
        "  backup [output-dir]  Create a zip backup of notes and datasets\n"
        "  restore <backup.zip>  Restore notes and datasets from a zip backup\n\n"
        "Examples:\n"
        f"  {program_name} create \"My Note\" \"hello world\"\n"
        f"  {program_name} list\n"
        f"  {program_name} search python\n"
        f"  {program_name} read my-note\n"
        f"  {program_name} create \"Task\" \"Finish docs\" --author \"Shocka\" --status draft --priority 1 --tags \"work,docs\"\n"
        f"  {program_name} update my-note --title \"New Title\"\n"
        f"  {program_name} update my-note --status active --priority 2\n"
        f"  {program_name} delete my-note\n"
        f"  {program_name} backup\n"
        f"  {program_name} backup /tmp/backups\n"
        f"  {program_name} restore /tmp/backups/notes-backup-2026-04-30T....zip\n"
    )
