def render_help(program_name: str = "python -m notes_app.cli.main") -> str:
    return (
        "Future Proof Notes CLI (phase-1 starter)\n\n"
        f"Usage: {program_name} [command]\n\n"
        "Commands:\n"
        "  help  Show this help text\n"
        "  list  List notes with metadata\n"
        "  search <query>  Search title, tags, and note body\n"
        "  create <title> <content>  Create a note\n"
        "  read <id>  Display a note by id or filename\n"
        "  update <id> [--title \"...\"] [--tags \"tag1,tag2\"] [--content \"...\"]  Update a note\n"
        "  delete <id>  Delete a note by id or filename\n\n"
        "Examples:\n"
        f"  {program_name} create \"My Note\" \"hello world\"\n"
        f"  {program_name} list\n"
        f"  {program_name} search python\n"
        f"  {program_name} read my-note\n"
        f"  {program_name} update my-note --title \"New Title\"\n"
        f"  {program_name} delete my-note\n"
    )
